### ISSUE TITLE
Hue dimmer switch not working.

### ISSUE THREAD

**Issue by etretti** [sebbebebbe/com.philips.hue.zigbee#8] opened 2018-03-11 14:11 UTC
pairs fine but cant execute any flows with it.
been broken since 1.5.4. still nothing in 1.5.7

**Comment by daka81** [comment] 2018-03-28 13:55
Any news on this? 
Stopped working after updating  to 1.5.8.

**Comment by etretti** [comment] 2018-04-03 15:07
ive tried reseting it, pulled battery, tried to implement it in diffrent flows. nothing. its a dead brick on my wall..... :( would be nice to hear something from the creator of the app.... @sebbebebbe

**Comment by sebbebebbe** [comment] 2018-04-03 18:27
Hi all, sorry that i have not answered your messages. I have not gotten any notifications about this issue until @etretti mentioned me in the post.

I have a few reports of this issue, however after analyzing the logfiles from a few Homeys having these issues i can´t see anything suspicious. This has led me to believe that it has to do with Athoms Zigbee implementation. Since this app does not have alot of logic right now and is mostly mapping device manufacturer id:s to the Homey app structure.

There might be an issue when non Hue devices are also added to the network.

I may rework the little logic i have for the Dimmer switch in the next update, although i should mention that there are as many reports of it working as there are it not working.  Please send me your apps logfile by pressing Alt-key while hovering over the app in Settings -> Apps.

**Comment by etretti** [comment] 2018-04-04 15:19
@sebbebebbe , sent you a log. thanks for responding :)

**Comment by mickeman** [comment] 2018-04-06 20:01
Hi, got the same problem with dimmer switch not working.
Happened today, have worked perfect several weeks before.
The only thing i have done today is added 2 hue white ambiance candle lights.
Don´t know if it is related but i wanted to let you know.
I have sent a log a few minutes ago.
@sebbebebbe

**Comment by AllG123** [comment] 2018-05-08 19:16
also having the same issues witk the dimmer for some time now, it worked great before. i have multple zigbee device als some aqara sensors, it stopped working after an homey update (if not mistaken 1.5.6) 
Dint have time to do some testing on my part untill now. 

While deleting the dimmer before re-adding the device to the network, in the smartphone app i got a error "driver id missing" Trying to delete the device through zigbee setting -> remove device no device was found. Fired up the old laptop and try to delete the device here, still no respond from device. Deleted the device anyway. 

Put the dimmer in pairing adding went fine, made new flow "turn on a hue bulb" nothing fancy. it does Nothing. 

In developer tools the device also turns up as an unknown device. all other seems ok to me, also device turns up in homey correctly.

Hope this helps

@sebbebebbe  LOG:  97844fbd-0fbb-47c4-ab5a-3320bbc9f265

**Comment by tomasrylander** [comment] 2018-06-15 20:21
Hi!

I also have the same issue and to give you even more information, I have just sent the log file
 999482a8-eecc-481e-863e-fa4a83c7d7da


tomas

**Comment by mickeman** [comment] 2018-06-15 23:06
Hi @sebbebebbe sent you another log 83733410-8032-4e57-963e-e7f30357674d
quick explain:
Everything has been working fine since (since April) i removed most of my lamps and has been controlling them with homey through my hue bridge.
Today i added the INNR app to homey and one SP 120.
Now one of the dimmers has stopped working but the other still works.
The one with network adress ending with ccf9 is NOT working.
The one with network adress ending with 9f89 is still working.
Both dimmers responds with green led when i push any button but nothing happens.
The lamps it´s controlling is working if i control them directly with homey.
Hope this helps to sort out what´s wrong.

/Micke

**Comment by sebbebebbe** [comment] 2018-06-25 10:51
Hi @mickeman thanks for the log, however I cannot see anything out of the ordinary.

I know that Athom has said that they eventually will write their own ZigBee implementation since the one they are using today is third party and not maintained anymore.

The app itself is only exposing which features should be available for the user for a specific model of unit. So there is no functionality for calling devices in the app that i can tweak with regards to devices not responding.

**Comment by Vincent75b** [comment] 2018-07-03 10:20
Hello, I have a similar problem. Lamps are working fine but the Dimmer Switch seems to loose connection after a few days. Tried to exlude and re-include the DS, which worked for only a few days again. 

Please let me know is a log file is helpful. (I can exclude and re-include, wait until the connection drops, make a log and let you know the timing)

**Comment by koktaildotcom** [comment] 2018-07-07 08:54
@sebbebebbe same problem here. The dimmer does not work anymore. The device doesn't response to any key pressed. The pairing is successful however.

**Comment by etretti** [comment] 2018-08-18 16:44
my dimmer switch just started working again, did not work yesterday, have not been working since i first posted this issue. no updates of apps or homey since 2 weeks ago..... really weird...

**Comment by koktaildotcom** [comment] 2018-08-31 13:47
@etretti I can confirm that the dimmer is now working again... Hope it will stay working..

**Comment by koktaildotcom** [comment] 2018-09-17 20:48
And the dimmer is not responding again

**Comment by slasktrat** [comment] 2018-12-02 20:43
I have the exact same issue. Worked perfectly for a while, then after adding another Hue bulb, the dimmer switch stopped working. Tried to remove and re-pair several times without any luck.

I notice however that when I start the app this line is printed in the very beginning.
(node:22399) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 __appInit listeners added. Use emitter.setMaxListeners() to increase limit

The error disappears if I limit the number of drivers, but that did not solve the issue with the dimmer switch :/

**Comment by JannickNijholt** [comment] 2019-07-08 15:38
After adding the Dimmer Switch it doesn't work with any Flow I add to it. It only gives me red lights after pressing a button.

My version is: 1.4.5
And my Homey (early 2019) is on: 2.3.0

**Comment by Hirostil** [comment] 2019-08-06 18:08
I just bought 2 Hue dimmer switch (RWL021) and it doesn't work with any Flow :(

Do you have an idea?

My version is: 1.4.5
And my Homey (early 2019) is on: 2.5.1

**Comment by sebbebebbe** [comment] 2019-09-21 07:43
Some people are still having issues with this. Keep reporting to Athom. Closing this issue since there is nothing i can do sadly.

**Closed as completed by sebbebebbe** 2019-09-21 07:43 UTC
