### ISSUE TITLE
Philips Motion Sensor works only for 24hours

### ISSUE THREAD

**Issue by sp1rr3** [sebbebebbe/com.philips.hue.zigbee#20] opened 2018-07-31 19:09 UTC
Hi, 
I added a philips motion sensor and when you add it it works and detect motion. but after ~24hours it stops working i can see the led on the motion sensor turn red but nothing in homey.
Tried rebooting homey dosent work, only thing that works is to remove and add the device again.

running version v1.3.0

**Comment by sebbebebbe** [comment] 2018-08-01 18:42
More or less duplicate of #21

**Closed as completed** 2019-03-06 11:48 UTC
