### ISSUE TITLE
cant link new bulb LCT012

### ISSUE THREAD

**Issue by iWelna** [sebbebebbe/com.philips.hue.zigbee#171] opened 2020-02-11 00:14 UTC
Hello,

 I have bought 2 bulbs  (PHILIPS HUE WHITE AND COLOR AMBIANCE 6,5W B39 E14 470 lum).
I have been trying to add them to Homey  for last two days, didnt happen.

scenerios:
1.  app with zigbee,  after removing bulb from bridge and trying find it in app as new device, it never get found and i get timeout message (tried many times).

2.Can't add it as generic zigbee - also never get found.

3. Both bulbs works with hue bridge normally, but with bridge homey app it gets added to homey, and then dont work ( wrong device id error).

All i could do was logging to API and get the infos from the 2 bulbs 

Bulb1:
```
{
	"state": {
		"on": true,
		"bri": 156,
		"hue": 25923,
		"sat": 242,
		"effect": "none",
		"xy": [
			0.1797,
			0.6754
		],
		"ct": 153,
		"alert": "none",
		"colormode": "hs",
		"reachable": true
	},
	"type": "Extended color light",
	"name": "Hue color light 1",
	"modelid": "LCT012",
	"manufacturername": "Philips",
	"uniqueid": "00:17:88:01:04:44:79:84-0b",
	"swversion": "1.29.0_r21169",
	"swconfigid": "EA9279F9",
	"productid": "Philips-LCT012-1-E14ECLv1"
}
```

Bulb2:
```

{
	"state": {
		"on": true,
		"bri": 254,
		"hue": 8418,
		"sat": 140,
		"effect": "none",
		"xy": [
			0.4573,
			0.41
		],
		"ct": 366,
		"alert": "none",
		"colormode": "ct",
		"reachable": true
	},
	"type": "Extended color light",
	"name": "Hue color light 2",
	"modelid": "LCT012",
	"manufacturername": "Philips",
	"uniqueid": "00:17:88:01:03:9e:d2:17-0b",
	"swversion": "1.46.13_r26312",
	"swconfigid": "8C67986F",
	"productid": "Philips-LCT012-1-E14ECLv1"
}
```

Please help.

thanks in advance

**Comment by JohanBendz** [comment] 2020-05-01 10:24
Hi. The LCT012 is already supported by the app. If you are unable to add the devices as generic Zigbee the issue is not in the app but with the pairing.

Try resetting your device and pair it again.

"Bulbs can also be reset if you have an official Philips Hue Dimmer Switch at home. With the light in question powered on, hold the Dimmer Switch close to it and hold down the On and Off buttons together for 10 seconds or so. When the light blinks and then stops blinking, the bulb is reset."

**Comment by iWelna** [comment] 2020-05-01 10:56
Hey,

I have already fixed problem with Hue Dimmer switch, reseted the bulbs and
could add them to Homey without problems.

Thanks for help and reply.


*Pozdrawiam*

*Patryk Pawliczuk*


pt., 1 maj 2020 o 12:24 Johan Bendz <notifications@github.com> napisał(a):

**Comment by JohanBendz** [comment] 2020-05-01 16:50
Good to hear! Closing the issue.

**Closed as completed by JohanBendz** 2020-05-01 16:50 UTC
