### ISSUE TITLE
Hue motion sensor regularly stops reporting

### ISSUE THREAD

**Issue by fkey3** [sebbebebbe/com.philips.hue.zigbee#185] opened 2020-05-12 20:04 UTC
I have several hue motion sensors.
The sensors connected via this app regularly stop reporting for a long (hours) time. Lux changes are not received by homey.
This screenshot is during sundown. When the sensor reports properly I see it going down to 1.
Moved most of my sensors back to the bridge because they are not reliable.

Problem is reported several rimes on the forum to. Sometimes referring to the reauired zigbee rewrite.
![0FCB7652-F027-4131-8134-AE576DECDD2A](https://user-images.githubusercontent.com/42219340/81739331-7317c200-949b-11ea-8df7-ef99758aebd7.jpeg)
And reporting again after 63min of radio silence
![01619CDB-77F8-47C7-943F-8A873B5B6D06](https://user-images.githubusercontent.com/42219340/81741688-377ef700-949f-11ea-9b87-dbeb2d6e4989.jpeg)

![1A57614E-28F8-46BD-A0FC-B1BE35259BED](https://user-images.githubusercontent.com/42219340/81739337-757a1c00-949b-11ea-8008-2e618411995f.jpeg)

I do see a remark in version 1.51: “ Hue Motion Sensor, fine tuning of reporting will hopefully make the device work better”

Hope that is a solution,

**Comment by JohanBendz** [comment] 2020-05-12 21:10
Hi @fkey3 and thanks for your feedback.

The problems with the Motion Sensors are sadly all to well known. Some complain while other users report that their sensors actually work as they should. The struggle to make the units work better continues!

I have a motion sensor on my desktop triggering a lamp to blink on movement. I'm running latest Test version of the app and the sensor has not missed a trigger for days now. It blinks the lamp within a second, stays triggered if I move within the reset time frame and goes back to "armed" mode if no movement has been detected.

When it comes to the lux changes there is a balance between draining the units battery vs getting all reports. You can change the min time between lux reports under settings. If you do not get any lux reading at all after pairing the unit please wait an hours or so and check again.

Please do try the Test version if you have not already.

And yeah, the much asked for Zigbee update will hopefully make a change.

// Johan

**Comment by fkey3** [comment] 2020-05-14 19:24
Thanks Johan for the quick response.
The sensor has been connected for over a year.

Al the sensors that I use for motion are on the bridge. The  non-responsiveness was too annoying.
The ones I use for lux are still on homey. Lux triggers are less frequent so I guess they fail to respond at times they are not required...

At times they completely stop sending to homey for hours (no motion no lux no temp).
Since it controls the lights in the livingroom, it leaves us in the dark (until we switch them on the oldfashioned way ;-) 

Greetings Frank

**Comment by edd-2** [comment] 2020-09-08 07:58
Hi Johan,
I have problems with one of my HUE sensors too. It seems like it's freezed. Saying it's detecting something and when I check the time it's been hours ago. After my nightly reboot (homey) sometimes it's working again. 
![afbeelding](https://user-images.githubusercontent.com/58843285/92448777-65f4b080-f1b9-11ea-9faf-82727cdc8f05.png)
You are talking about your latest version of your app. Test version? Is there any way I can download and install it on my Homey?
Thanks. 
Greetings, Ed

**Comment by rikadoo** [comment] 2020-10-06 19:22
Hi, i had the same problem on my Homey with your app with version v1 to v4 i think. So i was using the Hue Sensors via the Hue bridge. Now i have installed the Expirimental version of Homey V5 and i was hoping that this problem would be fixed with V5 and the big Zigbee update. But too bad i`m still having issues with Homey V5. Is this bug patchable in the new Zigbee driver or has this problem to do with other things?

**Comment by JohanBendz** [comment] 2020-10-06 19:31
Hi @rikadoo.
Can you please:
1. remove the device
2. restart Homey
3. add the device again and make sure it works
4. wait for it to stop working
5. create a crash report from the app and sign it with your name

This way I will be able to see what is happening and hopefully be able to fix any app related issue.
I will however not be able to help if the problem is with Homey, but I will send any info to Athom and work with them to fix it if so.

**Comment by rikadoo** [comment] 2020-10-06 20:12
Hi Johan, thank you for the reply. I`ve added the motion sensor as mentioned in your post. After i`m seeing that the sensor isn`t working anymore i will create an report and send it. Do you want me to place the report code here?

**Comment by JohanBendz** [comment] 2020-10-06 20:31
@rikadoo Great! Not needed to post it here, I will see it anyway. :)

**Comment by rikadoo** [comment] 2020-10-06 20:40
Ok:) i will let you know!

**Comment by rikadoo** [comment] 2020-10-07 20:02
I`ve got the problem back now on a other sensor on the top floor. I`ve made an diagnostic report and send it to Athom. I hope you can find the problem, its kind of annoying.

**Comment by rikadoo** [comment] 2020-11-29 16:58
Are there any updates regarding this issue? I got a new upate from Homey and it looks like my sensors are working again and it looks like it`s fixed for now atleast...

**Comment by AdamStoot** [comment] 2020-12-27 16:31
I'm having the same issue. I have notices that the sensor connects directly with the Homey when just paired, and then everything works fine. However, after a while it routes via another device (it is quite far away), and then it stops working. In this case, it routes via an Ikea bulb. Could it be that information is not transferred correctly when meshing?
A fix for this would be very appreciated!
![image](https://user-images.githubusercontent.com/69304508/103175295-300f3100-4869-11eb-8cd3-7521403fc01d.png)

**Comment by nielslbeck** [comment] 2021-01-24 06:41
I'm having the same issue with my sensors. My house is built without normal switches, so everything is controlled by the Homey, Hue Motion Sensors, Flic buttons and Sensative Strips Guard. However, my motion sensors sometimes lose the connection to Homey which is pretty annoying as the lights then won't turn on/off.

Here we have a fresh example from the kitchen ("Køkken" in Danish):
![image](https://user-images.githubusercontent.com/514291/105623029-afffcb00-5e16-11eb-88d5-288a81db2951.png)

I have 18 motion sensors in the house and some of them are connected to the Hue bridge (where all the lights are connected too, so I can use all the Hue apps available on the iPhone) but I have started moving the motion sensors to Homey as the response time is better with the direct connection. But it's a pain having to remove and reconnect the motion sensors again and again.

So I really hope this will be fixed even though my hopes aren't high given the history of this thread :-/

**Comment by JohanBendz** [comment] 2021-02-28 21:49
Drivers have been rewritten in firmware 5. Some sensors will have to be removed and paired again to work. Sorry for any inconvenience.

**Closed as completed by JohanBendz** 2021-02-28 21:49 UTC
Labels: bug
